### ISSUE TITLE
When is code available?

### ISSUE THREAD

**Issue by bschroedr** [YangLing0818/SGDiff#2]
I was just wondering when the code for this project will be available?

**Comment by YangLing0818** [comment]
Thanks for your interests in our SGDiff. This paper is currently under review. We will release the code and trained models upon acceptance.

**Comment by gauravspyke** [comment]
Hello Ling Yang, 

when will be the code available? Any tentative date? can i get your email?

**Comment by YangLing0818** [comment]
> I was just wondering when the code for this project will be available?

The code has been released

**Comment by YangLing0818** [comment]
> Hello Ling Yang,
> 
> when will be the code available? Any tentative date? can i get your email?

The code has been released

**Comment by bschroedr** [comment]
Thank you! I see you used the same GCN and dataset builders as sg2im. I've
looked through your code a lot and was trying to figure out where the
pretraining occurs. Could you point to where it happens (I see that scene
graphs get processed in CGIPModel, but it is only mentioned in a config
file)?

thanks for your help,
brigit
